version: '2'
services:
  nginx-proxy:
    image: quay.io/opsway/odoo-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - proxy-companion:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy      
  web-worker:
    image: web-worker
    environment:
      - VIRTUAL_HOST=your.domainname.com
      - LETSENCRYPT_HOST=your.domainname.com
      - LETSENCRYPT_EMAIL=mail@your.domainname.com
  odoo:
    image: odoo
